version: "3"

services:
  web:
    build: .
    ports:
      -  127.0.0.1:10001:8000
    # Let the init system handle signals for us.
    # among other things this helps shutdown be fast
    init: true
    volumes:
      - ./.env:/app/.env
      - ./db:/mnt/db
    # command: python manage.py runserver 0.0.0.0:8000
