[project]
name = "collect"
version = "0.1.0"
description = ""
authors = [{ name = "Mathieu Leplatre", email = "mathieu@leplat.re" }]
requires-python = "~=3.12.0"
readme = "README.md"
dependencies = [
    "django-taggit>=6.0.0,<7",
    "django~=6.0",
    "django-simple-history>=3.12.0,<4",
    "pillow>=10.4.0,<13",
    "django-imagekit>=5.0.0,<7",
    "python-decouple~=3.8",
    "dj-database-url>=2.2.0,<4",
    "pylibmagic>=0.5.0,<0.6",
    "python-magic>=0.4.27,<0.5",
    "gunicorn>=26.0.0,<27",
    "whitenoise>=6.7.0,<7",
    "psycopg2-binary>=2.9.12,<3",
    "django-storages>=1.14.6,<2",
    "google-cloud-storage>=3.12.0,<4",
    "boolean-py>=5.0",
    "ply>=3.11",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1,<10",
    "mypy>=2.1.0,<3",
    "pytest-cov>=5.0.0,<8",
    "ruff>=0.15.18,<0.16",
    "factory-boy>=3.3.3",
    "pytest-django>=4.11.1",
    "pytest-env>=1.1.4",
    "django-debug-toolbar>=7.0.0,<8",
    "djlint>=1.39.2,<2",
    "pytest-xdist>=3.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
extend-exclude = [
    "__pycache__",
    ".venv/",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E", "W",
    # flake8
    "F",
    # isort
    "I",
]
ignore = [
    # `format` will wrap lines.
    "E501",
]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "collect.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
env = [
    "COLLECT_SIGNUP_SECRETS_WORDS=t3st",
    "DJANGO_DEBUG=True",
    "DJANGO_INTERNAL_IPS=127.0.0.1",
    "DJANGO_CSRF_TRUSTED_ORIGINS=http://127.0.0.1",
    "DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost",
    "DJANGO_STATIC_ROOT=/tmp/django_static_root",
    "DJANGO_MEDIA_ROOT=/tmp/django_media_root",
]
