# Generated by Django 5.1 on 2024-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0002_uuidtaggeditem_collectable_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectable",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="historicalcollectable",
            name="description",
            field=models.TextField(default="", verbose_name="Description"),
        ),
    ]
