# Generated by Django 5.1 on 2024-08-23 16:02

from django.db import migrations, models

import collectable.validators


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0002_alter_collectable_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectable",
            name="photo",
            field=models.ImageField(
                help_text="Please provide a square JPEG image (.jpg, .jpeg)",
                upload_to="collectables/%Y/",
                validators=[
                    collectable.validators.MimetypeValidator(
                        ["image/jpg", "image/jpeg"]
                    ),
                    collectable.validators.SquareImageValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollectable",
            name="photo",
            field=models.TextField(
                help_text="Please provide a square JPEG image (.jpg, .jpeg)",
                max_length=100,
                validators=[
                    collectable.validators.MimetypeValidator(
                        ["image/jpg", "image/jpeg"]
                    ),
                    collectable.validators.SquareImageValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
    ]
