# Generated by Django 5.1 on 2024-08-26 15:43

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import collectable.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collectable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Please provide a square JPEG image (.jpg, .jpeg)",
                        upload_to="collectables/%Y/",
                        validators=[
                            collectable.validators.MimetypeValidator(
                                ["image/jpg", "image/jpeg"]
                            ),
                            collectable.validators.SquareImageValidator(),
                        ],
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collectable",
                "verbose_name_plural": "Collectables",
            },
        ),
        migrations.CreateModel(
            name="HistoricalCollectable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Created at"
                    ),
                ),
                (
                    "photo",
                    models.TextField(
                        help_text="Please provide a square JPEG image (.jpg, .jpeg)",
                        max_length=100,
                        validators=[
                            collectable.validators.MimetypeValidator(
                                ["image/jpg", "image/jpeg"]
                            ),
                            collectable.validators.SquareImageValidator(),
                        ],
                        verbose_name="Photo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "historical Collectables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Possession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.BooleanField(default=False, verbose_name="Likes")),
                ("wants", models.BooleanField(default=False, verbose_name="Wants")),
                ("owns", models.BooleanField(default=True, verbose_name="Owns")),
                (
                    "collectable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collectable.collectable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Possession",
                "verbose_name_plural": "Possessions",
                "unique_together": {("user", "collectable")},
            },
        ),
        migrations.AddField(
            model_name="collectable",
            name="possessions",
            field=models.ManyToManyField(
                through="collectable.Possession", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
