# Generated by Django 5.1 on 2025-06-03 07:45

from django.db import migrations, models

import collectable.validators


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0005_collectable__computed_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectable",
            name="_computed_tags",
            field=models.TextField(
                db_comment="Read only field to track tags history",
                editable=False,
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="collectable",
            name="photo",
            field=models.ImageField(
                help_text="Please provide a square JPEG image (.jpg, .jpeg)",
                upload_to="collectables/%Y/",
                validators=[
                    collectable.validators.MimetypeValidator(
                        ["image/jpg", "image/jpeg"]
                    ),
                    collectable.validators.SquareImageValidator(),
                    collectable.validators.MaxFileSizeValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollectable",
            name="_computed_tags",
            field=models.TextField(
                db_comment="Read only field to track tags history",
                editable=False,
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollectable",
            name="photo",
            field=models.TextField(
                help_text="Please provide a square JPEG image (.jpg, .jpeg)",
                max_length=100,
                validators=[
                    collectable.validators.MimetypeValidator(
                        ["image/jpg", "image/jpeg"]
                    ),
                    collectable.validators.SquareImageValidator(),
                    collectable.validators.MaxFileSizeValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
    ]
