# Generated by Django 5.2.6 on 2025-09-24 07:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import collectable.models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0006_alter_collectable__computed_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectable",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
        migrations.AddField(
            model_name="historicalcollectable",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
        migrations.CreateModel(
            name="DuplicateReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reported at"),
                ),
                (
                    "confirmed_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="duplicate_reports_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reports_2",
                        to="collectable.collectable",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reports_1",
                        to="collectable.collectable",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        default=collectable.models.get_unknown_user,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="duplicate_reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("original", models.F("duplicate")), _negated=True
                        ),
                        name="prevent_self_duplicate",
                    ),
                    models.UniqueConstraint(
                        fields=("original", "duplicate", "reporter"),
                        name="unique_duplicate_report",
                    ),
                ],
            },
        ),
    ]
