# Generated by Django 5.2.6 on 2025-10-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0006_alter_collectable__computed_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectable",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
        migrations.AddField(
            model_name="historicalcollectable",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
    ]
