# Generated by Django 5.2.6 on 2025-10-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import collectable.models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0007_collectable_hidden_historicalcollectable_hidden"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateReport",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "original_id",
                        "duplicate_id",
                        "reporter_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reported at"),
                ),
                (
                    "duplicate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_as_duplicate",
                        to="collectable.collectable",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_as_original",
                        to="collectable.collectable",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=models.SET(collectable.models.get_unknown_user),
                        related_name="duplicate_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("original", models.F("duplicate")), _negated=True
                        ),
                        name="prevent_self_duplicate",
                    ),
                    models.UniqueConstraint(
                        fields=("original", "duplicate", "reporter"),
                        name="unique_duplicate_report",
                    ),
                ],
            },
        ),
    ]
