# Generated by Django 6.0.7 on 2026-07-17 07:15

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count

import collectable.validators


def deduplicate_possessions(apps, schema_editor):
    """Merge duplicate (user, collectable) possessions before enforcing uniqueness.

    Older data may contain several Possession rows for the same user/collectable
    pair, which would make the unique constraint fail to apply. For each group we
    keep the oldest row, OR-ing the boolean flags of the duplicates into it so no
    "likes/wants/owns" information is lost, then delete the extras.
    """
    Possession = apps.get_model("collectable", "Possession")
    duplicates = (
        Possession.objects.values("user_id", "collectable_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for group in duplicates:
        rows = list(
            Possession.objects.filter(
                user_id=group["user_id"], collectable_id=group["collectable_id"]
            ).order_by("id")
        )
        keep, extras = rows[0], rows[1:]
        for extra in extras:
            keep.likes = keep.likes or extra.likes
            keep.wants = keep.wants or extra.wants
            keep.owns = keep.owns or extra.owns
            extra.delete()
        keep.save()


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0010_create_collectors_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="possession",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="collectable",
            name="photo",
            field=models.ImageField(
                help_text="Please provide a square JPEG image (.jpg, .jpeg)",
                upload_to="collectables/%Y/",
                validators=[
                    collectable.validators.MimetypeValidator(["image/jpeg"]),
                    collectable.validators.SquareImageValidator(),
                    collectable.validators.MaxFileSizeValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollectable",
            name="photo",
            field=models.TextField(
                help_text="Please provide a square JPEG image (.jpg, .jpeg)",
                max_length=100,
                validators=[
                    collectable.validators.MimetypeValidator(["image/jpeg"]),
                    collectable.validators.SquareImageValidator(),
                    collectable.validators.MaxFileSizeValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.RunPython(
            deduplicate_possessions, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="possession",
            constraint=models.UniqueConstraint(
                fields=("user", "collectable"), name="unique_possession"
            ),
        ),
    ]
