# Generated by Django 6.0.7 on 2026-07-31 14:25

from django.db import migrations, models

import collectable.validators


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0011_alter_possession_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectable",
            name="photo",
            field=models.ImageField(
                help_text="Please provide a square JPEG or PNG image (.jpg, .jpeg, .png)",
                upload_to="collectables/%Y/",
                validators=[
                    collectable.validators.MimetypeValidator(
                        ["image/jpeg", "image/png"]
                    ),
                    collectable.validators.SquareImageValidator(),
                    collectable.validators.MaxFileSizeValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollectable",
            name="photo",
            field=models.TextField(
                help_text="Please provide a square JPEG or PNG image (.jpg, .jpeg, .png)",
                max_length=100,
                validators=[
                    collectable.validators.MimetypeValidator(
                        ["image/jpeg", "image/png"]
                    ),
                    collectable.validators.SquareImageValidator(),
                    collectable.validators.MaxFileSizeValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
    ]
