# Generated by Django 6.1.1 on 2026-09-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0012_add_png_photo_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectable",
            name="copies_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="The number of copies of this collectable.",
                null=True,
                verbose_name="Copies count",
            ),
        ),
        migrations.AddField(
            model_name="historicalcollectable",
            name="copies_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="The number of copies of this collectable.",
                null=True,
                verbose_name="Copies count",
            ),
        ),
    ]
