# Generated by Django 6.1.1 on 2026-09-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0013_collectable_copies_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectable",
            name="source_file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Original editable file (e.g. .pdf, .png, .svg, ...)",
                null=True,
                upload_to="collectables/%Y/source/",
                verbose_name="Source file",
            ),
        ),
        migrations.AddField(
            model_name="historicalcollectable",
            name="source_file",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Original editable file (e.g. .pdf, .png, .svg, ...)",
                max_length=100,
                null=True,
                verbose_name="Source file",
            ),
        ),
    ]
