# Generated by Django 6.1.1 on 2026-09-20 20:39

from django.db import migrations, models

import collectable.validators


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0014_collectable_source_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectable",
            name="photo",
            field=models.ImageField(
                help_text="Please provide a square JPEG or PNG image (.jpg, .jpeg, .png)",
                upload_to="collectables/%Y/",
                validators=[
                    collectable.validators.MimetypeValidator(
                        ["image/jpeg", "image/png"]
                    ),
                    collectable.validators.SquareImageValidator(),
                    collectable.validators.MaxFileSizeValidator(),
                    collectable.validators.MaxImagePixelsValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="collectable",
            name="source_file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Original editable file (e.g. .pdf, .png, .svg, ...)",
                null=True,
                upload_to="collectables/%Y/source/",
                validators=[
                    collectable.validators.FileExtensionValidator(),
                    collectable.validators.MaxFileSizeValidator(
                        "COLLECTABLE_SOURCE_FILE_MAX_UPLOAD_BYTES"
                    ),
                ],
                verbose_name="Source file",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollectable",
            name="photo",
            field=models.TextField(
                help_text="Please provide a square JPEG or PNG image (.jpg, .jpeg, .png)",
                max_length=100,
                validators=[
                    collectable.validators.MimetypeValidator(
                        ["image/jpeg", "image/png"]
                    ),
                    collectable.validators.SquareImageValidator(),
                    collectable.validators.MaxFileSizeValidator(),
                    collectable.validators.MaxImagePixelsValidator(),
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcollectable",
            name="source_file",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Original editable file (e.g. .pdf, .png, .svg, ...)",
                max_length=100,
                null=True,
                validators=[
                    collectable.validators.FileExtensionValidator(),
                    collectable.validators.MaxFileSizeValidator(
                        "COLLECTABLE_SOURCE_FILE_MAX_UPLOAD_BYTES"
                    ),
                ],
                verbose_name="Source file",
            ),
        ),
    ]
