# Generated by Django 6.1.1 on 2026-09-21 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0014_collectable_source_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="possession",
            name="swaps",
            field=models.BooleanField(
                default=False,
                help_text="I have a spare copy of this one, available for swap.",
                verbose_name="Spare",
            ),
        ),
        migrations.AddConstraint(
            model_name="possession",
            constraint=models.CheckConstraint(
                condition=models.Q(("owns", False), ("swaps", True), _negated=True),
                name="swap_requires_owns",
            ),
        ),
    ]
