# Generated by Django 6.1.1 on 2026-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0015_possession_swaps_possession_swap_requires_owns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="possession",
            name="likes",
            field=models.BooleanField(
                default=False, help_text="I like this one.", verbose_name="Likes"
            ),
        ),
        migrations.AlterField(
            model_name="possession",
            name="owns",
            field=models.BooleanField(
                default=True, help_text="I own this one.", verbose_name="Owns"
            ),
        ),
        migrations.AlterField(
            model_name="possession",
            name="wants",
            field=models.BooleanField(
                default=False,
                help_text="I am looking for this one.",
                verbose_name="Wants",
            ),
        ),
    ]
