# Generated by Django 6.1.1 on 2026-09-21 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collectable", "0016_alter_possession_likes_alter_possession_owns_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collectable",
            index=models.Index(
                fields=["hidden", "-created_at"], name="collectable_visible_recent"
            ),
        ),
    ]
