name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: make install

    - name: Lint
      run: make lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: make install

    - name: Run tests
      run: make test

  end2end:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare folders
      run: |
        mkdir -p media-folder/uploads
        chmod -R 777 media-folder
        cp env.local .env

    - name: Build Docker container
      run: docker compose build

    - name: Initialize database
      run: docker compose run init

    - name: Add demo data
      run: docker compose run demo

    - name: Run application containers
      run: docker compose up -d

    - name: Check app liveliness
      run: |
        for i in {1..20}; do
          curl --fail --silent --location http://127.0.0.1:8000/health/ && break
          echo "Waiting for app to start..."
          sleep 3
        done

    - name: Check app readiness
      run: |
        for i in {1..20}; do
          curl --fail --silent --location http://127.0.0.1:8000/readiness/ && break
          echo "Waiting for app to be ready..."
          sleep 3
        done

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: make install

    - name: Run Playwright Tests
      run: make browser-test

    - name: Show app logs
      if: failure()
      run: docker compose logs -n 1000 web || true

    - name: Upload Playwright test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playwright-artifacts
        path: test-results/
