name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: make install

    - name: Lint
      run: make lint

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: make install

    - name: Run tests
      run: make test

  end2end:
    runs-on: ubuntu-latest
    needs: [test]

    env:
      DJANGO_DATABASE_URL: postgres://dbuser:dbpassword@db.collect-net:5432/collectdb

    steps:
    - name: Create Docker network
      run: docker network create collect-net

    - name: Start DB service manually
      run: |
        docker run --detach --name db \
          --network collect-net \
          -e POSTGRES_DB=collectdb \
          -e POSTGRES_USER=dbuser \
          -e POSTGRES_PASSWORD=dbpassword \
          -p 5432:5432 postgres:15

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          docker run --rm --network collect-net postgres:15 \
            pg_isready -h db -U dbuser && break
          echo "Waiting for db..."
          sleep 3
        done

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker container
      run: docker build -t collect-app .

    - name: Initialize database
      run: |
        docker run --rm \
          --network collect-net \
          -e DJANGO_DATABASE_URL=${DJANGO_DATABASE_URL} \
          collect-app \
          uv run manage.py migrate
        docker run --rm \
          --network collect-net \
          -e DJANGO_DATABASE_URL=${DJANGO_DATABASE_URL} \
          collect-app \
          uv run manage.py smart_create_user testuser testpass

    - name: Load demo data
      run: |
        docker run --rm \
          --network collect-net \
          -e DJANGO_DATABASE_URL=${DJANGO_DATABASE_URL} \
          -v `pwd`/demo:/mnt/demo \
          -v `pwd`/media-folder:/mnt/media:rw \
          collect-app \
          uv run manage.py loadfolder testuser /mnt/demo/

    - name: Run app container
      run: |
        docker run --detach \
          --network collect-net \
          -p 8000:8000 \
          --name test-collect-app \
          -e DJANGO_DATABASE_URL=${DJANGO_DATABASE_URL} \
          -v `pwd`/media-folder:/mnt/media:rw \
          collect-app

    - name: Wait for app to be ready
      run: |
        for i in {1..20}; do
          curl --fail --silent --location http://127.0.0.1:8000/health/ && break
          echo "Waiting for app to start..."
          sleep 3
        done

    - name: Check app readiness
      run: |
        for i in {1..20}; do
          curl --fail --silent --location http://127.0.0.1:8000/readiness/ && break
          echo "Waiting for app to be ready..."
          sleep 3
        done

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: make install

    - name: Run Playwright Tests
      run: make browser-test

    - name: Show app logs
      if: failure()
      run: docker logs test-collect-app || true

    - name: Upload Playwright test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: playwright-artifacts
        path: test-results/
